contact_links:
  - name: ğŸ‡ Live Chat
    url: https://discord.gg/8BmnndXHp6
    about: Join our Discord server to get answers to your questions ASAP
  - name: ğŸŒ Slow chat
    url: https://github.com/MarcusOtter/discord-needle/discussions
    about: If you prefer to not use Discord, you may also open a discussion here on GitHub
